#!/bin/bash
# Kidpen.space Azure Deployment Script
# Deploy infrastructure and applications to Azure Container Apps
#
# Usage: ./deploy.sh [dev|staging|prod] [--infra-only|--apps-only]
#
# Prerequisites:
#   - Azure CLI installed and logged in (az login)
#   - Docker installed for building images
#   - Bicep CLI installed (az bicep install)

set -euo pipefail

# Configuration
ENVIRONMENT="${1:-dev}"
DEPLOY_MODE="${2:-all}"  # all, infra-only, apps-only
LOCATION="southeastasia"  # Closest to Thailand
RESOURCE_GROUP="kidpen-${ENVIRONMENT}-rg"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }
log_success() { echo -e "${GREEN}✅ $1${NC}"; }
log_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
log_error() { echo -e "${RED}❌ $1${NC}"; exit 1; }

# Validate environment
validate_env() {
    case $ENVIRONMENT in
        dev|staging|prod) ;;
        *) log_error "Invalid environment: $ENVIRONMENT. Use dev, staging, or prod." ;;
    esac
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."

    if ! command -v az &> /dev/null; then
        log_error "Azure CLI not found. Install from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    fi

    if ! az account show &> /dev/null; then
        log_error "Not logged in to Azure. Run 'az login' first."
    fi

    if ! command -v docker &> /dev/null; then
        log_warning "Docker not found. Required for building container images."
    fi

    log_success "Prerequisites check passed"
}

# Create resource group if not exists
create_resource_group() {
    log_info "Creating resource group: $RESOURCE_GROUP"

    if az group show --name "$RESOURCE_GROUP" &> /dev/null; then
        log_info "Resource group already exists"
    else
        az group create \
            --name "$RESOURCE_GROUP" \
            --location "$LOCATION" \
            --tags project=kidpen environment="$ENVIRONMENT" managedBy=script
        log_success "Resource group created"
    fi
}

# Generate secure passwords for dev environment
generate_passwords() {
    if [ "$ENVIRONMENT" == "dev" ]; then
        log_info "Generating secure passwords for dev environment..."

        POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)
        REDIS_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)

        # Update parameters file
        sed -i "s/REPLACE_WITH_SECURE_PASSWORD/${POSTGRES_PASSWORD}/" "${SCRIPT_DIR}/parameters.dev.json"

        log_success "Passwords generated"
        log_warning "Save these passwords securely:"
        echo "  PostgreSQL: $POSTGRES_PASSWORD"
        echo "  Redis: Will be auto-generated by Azure"
    fi
}

# Deploy infrastructure using Bicep
deploy_infrastructure() {
    log_info "Deploying infrastructure with Bicep..."

    local PARAMS_FILE="${SCRIPT_DIR}/parameters.${ENVIRONMENT}.json"

    if [ ! -f "$PARAMS_FILE" ]; then
        log_error "Parameters file not found: $PARAMS_FILE"
    fi

    # For dev, we need to provide passwords inline
    if [ "$ENVIRONMENT" == "dev" ]; then
        POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)

        az deployment group create \
            --resource-group "$RESOURCE_GROUP" \
            --template-file "${SCRIPT_DIR}/main.bicep" \
            --parameters environment="$ENVIRONMENT" \
            --parameters location="$LOCATION" \
            --parameters postgresPassword="$POSTGRES_PASSWORD" \
            --parameters redisPassword="auto-generated" \
            --verbose
    else
        az deployment group create \
            --resource-group "$RESOURCE_GROUP" \
            --template-file "${SCRIPT_DIR}/main.bicep" \
            --parameters "@$PARAMS_FILE" \
            --verbose
    fi

    log_success "Infrastructure deployed"
}

# Get deployment outputs
get_outputs() {
    log_info "Retrieving deployment outputs..."

    OUTPUTS=$(az deployment group show \
        --resource-group "$RESOURCE_GROUP" \
        --name main \
        --query properties.outputs \
        -o json 2>/dev/null || echo "{}")

    ACR_LOGIN_SERVER=$(echo "$OUTPUTS" | jq -r '.containerRegistryLoginServer.value // empty')
    FRONTEND_URL=$(echo "$OUTPUTS" | jq -r '.frontendUrl.value // empty')
    BACKEND_URL=$(echo "$OUTPUTS" | jq -r '.backendUrl.value // empty')

    if [ -z "$ACR_LOGIN_SERVER" ]; then
        # Fallback to querying directly
        ACR_NAME=$(az acr list --resource-group "$RESOURCE_GROUP" --query "[0].name" -o tsv)
        ACR_LOGIN_SERVER="${ACR_NAME}.azurecr.io"
    fi

    export ACR_LOGIN_SERVER FRONTEND_URL BACKEND_URL
}

# Build and push container images
build_and_push_images() {
    log_info "Building and pushing container images..."

    get_outputs

    if [ -z "$ACR_LOGIN_SERVER" ]; then
        log_error "Could not determine ACR login server"
    fi

    # Login to ACR
    log_info "Logging in to Azure Container Registry..."
    az acr login --name "${ACR_LOGIN_SERVER%%.*}"

    # Build and push frontend
    log_info "Building frontend image..."
    docker build \
        -t "${ACR_LOGIN_SERVER}/kidpen-frontend:latest" \
        -t "${ACR_LOGIN_SERVER}/kidpen-frontend:$(git rev-parse --short HEAD)" \
        -f "${PROJECT_ROOT}/apps/frontend/Dockerfile" \
        "${PROJECT_ROOT}"

    log_info "Pushing frontend image..."
    docker push "${ACR_LOGIN_SERVER}/kidpen-frontend:latest"
    docker push "${ACR_LOGIN_SERVER}/kidpen-frontend:$(git rev-parse --short HEAD)"

    # Build and push backend
    log_info "Building backend image..."
    docker build \
        -t "${ACR_LOGIN_SERVER}/kidpen-backend:latest" \
        -t "${ACR_LOGIN_SERVER}/kidpen-backend:$(git rev-parse --short HEAD)" \
        -f "${PROJECT_ROOT}/backend/Dockerfile" \
        "${PROJECT_ROOT}/backend"

    log_info "Pushing backend image..."
    docker push "${ACR_LOGIN_SERVER}/kidpen-backend:latest"
    docker push "${ACR_LOGIN_SERVER}/kidpen-backend:$(git rev-parse --short HEAD)"

    log_success "Container images built and pushed"
}

# Update container apps with new images
update_container_apps() {
    log_info "Updating container apps..."

    get_outputs

    # Update frontend
    az containerapp update \
        --name "kidpen-${ENVIRONMENT}-frontend" \
        --resource-group "$RESOURCE_GROUP" \
        --image "${ACR_LOGIN_SERVER}/kidpen-frontend:latest"

    # Update backend
    az containerapp update \
        --name "kidpen-${ENVIRONMENT}-backend" \
        --resource-group "$RESOURCE_GROUP" \
        --image "${ACR_LOGIN_SERVER}/kidpen-backend:latest"

    log_success "Container apps updated"
}

# Configure custom domain
configure_custom_domain() {
    log_info "Configuring custom domain: kidpen.space"

    # This requires DNS to be configured first
    # Add CNAME record pointing to the Container App FQDN

    log_warning "Manual steps required:"
    echo "1. Add CNAME record for kidpen.space pointing to:"
    echo "   $(az containerapp show -n kidpen-${ENVIRONMENT}-frontend -g $RESOURCE_GROUP --query properties.configuration.ingress.fqdn -o tsv)"
    echo ""
    echo "2. Run the following command after DNS propagation:"
    echo "   az containerapp hostname add -n kidpen-${ENVIRONMENT}-frontend -g $RESOURCE_GROUP --hostname kidpen.space"
    echo "   az containerapp hostname bind -n kidpen-${ENVIRONMENT}-frontend -g $RESOURCE_GROUP --hostname kidpen.space --environment kidpen-${ENVIRONMENT}-env"
}

# Print summary
print_summary() {
    log_success "Deployment complete!"
    echo ""
    echo "🎉 Kidpen.space Azure Deployment Summary"
    echo "========================================"
    echo "Environment: $ENVIRONMENT"
    echo "Resource Group: $RESOURCE_GROUP"
    echo "Location: $LOCATION"
    echo ""

    get_outputs

    echo "🌐 URLs:"
    echo "  Frontend: $FRONTEND_URL"
    echo "  Backend:  $BACKEND_URL"
    echo ""
    echo "📦 Container Registry: $ACR_LOGIN_SERVER"
    echo ""
    echo "💰 Estimated Monthly Cost: ~\$166/month"
    echo "  - Container Apps: ~\$60-90 (scale-to-zero enabled)"
    echo "  - PostgreSQL B1ms: ~\$13"
    echo "  - Redis Basic C0: ~\$16"
    echo "  - Storage: ~\$5-10"
    echo "  - CDN: ~\$0-10"
    echo ""
    echo "📚 Next Steps:"
    echo "  1. Configure DNS for kidpen.space"
    echo "  2. Add SSL certificate"
    echo "  3. Set up CI/CD pipeline"
    echo "  4. Configure monitoring alerts"
}

# Main execution
main() {
    echo ""
    echo "🚀 Kidpen.space Azure Deployment"
    echo "================================="
    echo "Environment: $ENVIRONMENT"
    echo "Mode: $DEPLOY_MODE"
    echo ""

    validate_env
    check_prerequisites

    case $DEPLOY_MODE in
        infra-only)
            create_resource_group
            deploy_infrastructure
            ;;
        apps-only)
            build_and_push_images
            update_container_apps
            ;;
        all|*)
            create_resource_group
            deploy_infrastructure
            build_and_push_images
            update_container_apps
            ;;
    esac

    print_summary
    configure_custom_domain
}

main "$@"
